language: go
go:
- 1.2
- 1.3
env:
  matrix:
  - PGPASSWORD=tokenserver
  global:
    secure: CdbFy8BnHMZAhajT1obdqhJ3hr88LotYTV+TnJLeEcsmWL450uXCexI+rRiTmoxFz5NtFLcJ+jozXKJwnlNH/gDe/aBl0QRoPsWJkIw04BoCiiqmjTksWQlmlRpA9xT7UulBITajyJtXgp1eQgXxD0YUWL5LTRkPnO197arkLcc=
addons:
  postgresql: '9.3'
before_script:
- psql -c "create user syncserver with password 'syncserver';" -U postgres
- psql -c 'create database syncserver owner syncserver;' -U postgres
- psql -f setup.sql -U syncserver -d syncserver

deploy:
  provider: releases
  api-key: $TOKEN
  file: moz-syncserver
  skip_cleanup: true
  on:
    tags: true
    all_branches: true

